reman_2/urls.py
from django.urls import path

from .views import index, upload_excel, root_materials, sorting, settings, disassembly, other_materials, recondition

app_name = "reman_2"

urlpatterns = [
    path("reman_2", index, name='index'),
    path("reman_2/upload_excel", upload_excel, name='upload_excel'),
    path("reman_2/root_materials", root_materials, name='root_materials'),
    path("reman_2/sorting", sorting, name='sorting'),
    path("reman_2/disassembly", disassembly, name='disassembly'),
    path("reman_2/recondition", recondition, name='recondition'),
    path("reman_2/settings", settings, name='settings'),
    path("reman_2/other_materials", other_materials, name='other_materials'),
]

reman_2/templates/reman_2/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reman Regeneration Rate Reporting</title>
    <style>
        @font-face {
            font-family: 'Noto Sans';
            src: url('/media/fonts/NotoSans-Regular.ttf');
            font-weight: bold;
        }

        @font-face {
            font-family: 'Noto Sans';
            src: url('/media/fonts/NotoSans-Light.ttf');
            font-weight: normal;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: 'Noto Sans';
        }
        
        body {
            display: flex;
            height: 100vh;
            max-width: 100vw;
            background-image: url('/static/reman/reman_bg.jpg');
            background-size: cover;
            background-attachment: fixed;
        }

        .menu {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            max-width: 100vw;
            height: 5vh;
            min-height: 32px;
            background-color: hsla(200, 10%, 20%, 1);
            display: flex;
            flex-flow: row;
            color: white;
            justify-content: space-between;
        }
        
        .menu-item {
            cursor: pointer;
            display: flex;
            flex-grow: 1;
            flex-shrink: 1;
            justify-content: center;
            align-items: center;
        }

        .menu-item:hover {
            background-color: hsla(200, 50%, 20%, 1);
        }
    </style>
    {% block style %}
    {% endblock %}

    {% block scripts-top %}
    {% endblock %}
</head>
<body>
    <div class="menu">
        <div class="menu-item" onclick="window.location='{% url "reman_2:upload_excel" %}'">Nahrání souborů</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:root_materials" %}'">CC materiály</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:other_materials" %}'">Jiné materiály</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:sorting" %}'">Sorting</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:disassembly" %}'">Demontáž</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:recondition" %}'">Rekondice</div>
        <div class="menu-item" onclick="window.location='{% url "reman_2:settings" %}'">&#129520;</div>
    </div>
    {% block body %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}
</body>
</html>

reman_2/templates/reman_2/components.html
{% extends 'reman_2/base.html' %}

{% block style %}
<style>
    table {
        user-select: none;
        position: relative;
        top: 5vh;
        max-width: 100%;
        width: 100vw;
        height: 95vh;
        border: 1px solid lightgray;
        border-collapse: collapse;
        color: white;
        font-size: small;
        background-color: hsla(100, 50%, 5%, .9);
    }

    thead {
        position: sticky;
        top: 0vh;
        background-color: black;
    }

    tbody {
        overflow-y: scroll;
        max-height: 95vh;
    }

    tr {
        border-bottom: 1px solid lightgray;
    }

    tr:nth-child(even) {
        background-color: hsla(200, 50%, 20%, .9);
    }

    td {
        padding: 0 .25rem;
    }
</style>
{% endblock %}
{% block body %}

<table>
    <thead>
        <tr>
            <th>Order</th>
            <th>Type</th>
            <th>Requirement qty</th>
            <th>Withdrawn qty</th>
            <th>Material</th>
            <th>Pegged requirement</th>
            <th>NOK</th>
        </tr>

    </thead>

    <tbody>
        {% for row in components %}
        <tr>
            <td>{{row.order}}</td>
            <td>{{row.order.}}</td>
            <td>{{row.requirement_quantity}}</td>
            <td>{{row.quantity_withdrawn}}</td>
            <td>{{row.material}}</td>
            <td>{{row.pegged_requirement}}</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

reman_2/templates/reman_2/disassembly.html
{% extends 'reman_2/base.html' %}

{% block style %}
<style>
    div {
        color: white;
    }

    table {
        position: relative;
        top: 5vh;
        max-height: 95vh;
        /* width: 200vw; */
        overflow: auto;
        max-width: 200vw;
        min-width: 100vw;
        border: 1px solid lightgray;
        border-collapse: collapse;
        color: white;
        font-size: small;
        table-layout: fixed;
        background-color: hsla(100, 50%, 5%, .9);
        cursor: pointer;
    }

    thead {
        position: sticky;
        top: 0vh;
        background-color: black;
    }
</style>
{% endblock %}

{% block scripts-top %}
<script src="/static/xlsx.full.min.js"></script>
{% endblock %}

{% block body %}

<div class="wrapper">
    <table id="table">
        <thead>
            <tr id="table-heading">
                <th>Zákazník</th>
                <th>Skupina FG materiálů</th>
                <th>Skupinový výsledek</th>
                <th>FG materiál</th>
                <th>CC in</th>
                <th>FG exp</th>
                <th>FG out</th>
                <th>FG rate %</th>
                <th>FG NOK</th>
            </tr>
        </thead>

        <tbody>
        </tbody>
    </table>
</div>


{% endblock %}

{% block scripts %}
<script>

    const data = {{results|safe}}
    const tableBody = document.querySelector('tbody');

    populateTable(data);

    function populateTable(data) {

        var rowsCount = 0
        var customerIndices = new Map();
        var cmGroupIndices = new Map();
        var cmGroupResults = new Array();
        var cmIndices = new Map();
        var cmResults = new Array();
        var qmResults = new Array();
        var damageCodes = new Set();
        var initial = 0
        var excludedKeys = ['table_rows', 'qty_in', 'qty_out', 'qty_wanted', 'rate_component_material', 'rate_material_group', 'rate_root_material', 'rate_cm_group', 'no_of_different_cm', 'q3']

        for (const customer of Object.keys(data)) {
            rowsCount += data[customer]['table_rows'];
            customerIndices.set(customer, data[customer]['table_rows']);
            for (const cmMaterialGroup of Object.keys(data[customer])) {
                if (!(excludedKeys.includes(cmMaterialGroup))) {
                    cmGroupIndices.set(`${cmMaterialGroup}|${customer}`, data[customer][cmMaterialGroup]['table_rows'])
                }
                for (const key of Object.keys(data[customer][cmMaterialGroup])) {
                    if (key == 'rate_cm_group') {
                        cmGroupResults.push(data[customer][cmMaterialGroup]['rate_cm_group'])
                    }
                }

                for (const cm of Object.keys(data[customer][cmMaterialGroup])) {
                    if (!(excludedKeys.includes(cm))) {
                        cmIndices.set(`${cm}|${customer}`, 1);
                        let resultsArray = new Array();
                        resultsArray.push(data[customer][cmMaterialGroup][cm]['qty_in']);
                        resultsArray.push(data[customer][cmMaterialGroup][cm]['qty_wanted']);
                        resultsArray.push(data[customer][cmMaterialGroup][cm]['qty_out']);
                        resultsArray.push(data[customer][cmMaterialGroup][cm]['rate_component_material']);
                        cmResults.push(resultsArray)

                        let resultsMap = new Map();

                        for (const order of Object.keys(data[customer][cmMaterialGroup][cm]['q3'])) {
                            resultsMap.set(order, data[customer][cmMaterialGroup][cm]['q3'][order])
                        }

                        qmResults.push(resultsMap)
                    }

                }
            }
        }

        for (let i = 0; i < rowsCount; i++) {
            let newRow = document.createElement('tr');
            for (let j = 0; j < 9; j++) {
                let newCell = document.createElement('td');
                newCell.textContent = "test";
                newRow.append(newCell);
            }
            tableBody.append(newRow);
        }

        let customerColumnCells = Array.from(tableBody.querySelectorAll('tr > td:first-of-type'));
        let cmGroupColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(2)'));
        let cmGroupResultsColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(3)'));
        let cmColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(4)'));
        let cmInColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(5)'));
        let cmExpColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(6)'));
        let cmOutColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(7)'));
        let cmRateColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(8)'));
        let cmQ3ColumnCells = Array.from(tableBody.querySelectorAll('tr > td:nth-of-type(9)'));

        for (let [customer, customerRowSpan] of customerIndices) {
            customerColumnCells[initial].textContent = customer;
            customerColumnCells[initial].rowSpan = customerRowSpan;
            customerColumnCells[initial].dataset.spanned = 'true';
            initial = customerRowSpan;
        }

        initial = 0
        tempIndex = 0

        for (let [cmMaterialGroup, cmMaterialGroupRowSpan] of cmGroupIndices) {
            cmGroupColumnCells[initial].textContent = cmMaterialGroup.split("|")[0];
            cmGroupColumnCells[initial].rowSpan = cmMaterialGroupRowSpan;
            cmGroupColumnCells[initial].dataset.spanned = 'true';

            cmGroupResultsColumnCells[initial].textContent = `${Math.round((parseFloat(cmGroupResults[tempIndex]) * 100) * 100) / 100}%`;
            cmGroupResultsColumnCells[initial].rowSpan = cmMaterialGroupRowSpan;
            cmGroupResultsColumnCells[initial].dataset.spanned = 'true';

            initial = initial + cmMaterialGroupRowSpan;
            tempIndex += 1;
        }

        initial = 0
        tempIndex = 0

        for (let [cm, cmRowSpan] of cmIndices) {
            cmColumnCells[initial].textContent = cm.split("|")[0];
            cmColumnCells[initial].rowSpan = cmRowSpan;
            cmColumnCells[initial].dataset.spanned = 'true';
            
            cmInColumnCells[initial].textContent = cmResults[tempIndex][0];
            cmInColumnCells[initial].rowSpan = cmRowSpan;
            cmInColumnCells[initial].dataset.spanned = 'true';

            cmExpColumnCells[initial].textContent = cmResults[tempIndex][1];
            cmExpColumnCells[initial].rowSpan = cmRowSpan;
            cmExpColumnCells[initial].dataset.spanned = 'true';

            cmOutColumnCells[initial].textContent = cmResults[tempIndex][2];
            cmOutColumnCells[initial].rowSpan = cmRowSpan;
            cmOutColumnCells[initial].dataset.spanned = 'true';

            cmRateColumnCells[initial].textContent = `${Math.round(cmResults[tempIndex][3] * 100)}%`;
            cmRateColumnCells[initial].rowSpan = cmRowSpan;
            cmRateColumnCells[initial].dataset.spanned = 'false';

            let sum = 0
            if (qmResults[tempIndex].has('damage_codes')) {
                Object.entries(qmResults[tempIndex].get('damage_codes')).map(arr => {
                    sum += arr[1]
                    damageCodes.add(arr[0]);
                });
            }
            cmQ3ColumnCells[initial].textContent = sum;
            cmQ3ColumnCells[initial].title = qmResults[tempIndex].has('damage_codes') ? Object.entries(qmResults[tempIndex].get('damage_codes')) : "0";
            cmQ3ColumnCells[initial].rowSpan = cmRowSpan;
            cmQ3ColumnCells[initial].dataset.spanned = 'true';

            initial = initial + cmRowSpan;
            tempIndex += 1
        }

        damageCodes.forEach(damageCode => {
            let damageCodeTh = document.createElement('th');
            damageCodeTh.textContent = damageCode;
            damageCodeTh.dataset.damageCode = damageCode;
            document.getElementById('table-heading').append(damageCodeTh);
            for (row of tableBody.rows) {
                let newCell = row.insertCell(-1);
                newCell.textContent = 0;
            }
        })

        qmResults.forEach((qmResultsMap, index) => {
            let tableRow = index;
            if (qmResultsMap.has('damage_codes')) {
                for (const [damageCode, damageQty] of Object.entries(qmResultsMap.get('damage_codes'))) {
                    tableBody.rows[tableRow].cells[document.querySelector(`[data-damage-code="${damageCode}"]`).cellIndex].textContent = damageQty;
                    // console.log(document.querySelector(`[data-damage-code="${damageCode}"]`).cellIndex);
                }
                // console.log(tableBody.rows[index].);
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(9)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(8)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(7)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(6)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(5)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })


        tableBody.querySelectorAll('tr > td:nth-of-type(4)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:nth-of-type(3)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })
        
        tableBody.querySelectorAll('tr > td:nth-of-type(2)').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })

        tableBody.querySelectorAll('tr > td:first-of-type').forEach(cell => {
            if (!(cell.dataset.spanned)) {
                cell.remove();
            }
        })
    }

    document.addEventListener('keydown', (e) => {
        if (String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
            let workbook = XLSX.utils.table_to_book(document.getElementById("table"));
            XLSX.writeFile(workbook, "Disassembly.xlsb");
        }
    })

</script>
{% endblock %}

reman_2/templates/reman_2/index.html
{% extends 'reman_2/base.html' %}

reman_2/templates/reman_2/other_materials.html
{% extends 'reman_2/base.html' %}

{% block style %}
<style>
    table {
        user-select: none;
        position: relative;
        top: 5vh;
        max-width: 100%;
        height: 95vh;
        border: 1px solid lightgray;
        border-collapse: collapse;
        color: white;
        font-size: small;
        background-color: hsla(100, 50%, 5%, .9);
        table-layout: fixed;
    }

    thead {
        position: sticky;
        top: 0vh;
        background-color: black;
    }

    th {
        text-align: left;
    }

    tbody {
        overflow-y: scroll;
        max-height: 95vh;
    }

    tr {
        border-bottom: 1px solid lightgray;
    }

    tr:nth-child(even) {
        background-color: hsla(200, 50%, 20%, .9);
    }

    td {
        padding: 0 .25rem;
    }

    td:not(:last-of-type) {
        border-right: 1px solid white;
    }

    input {
        background-color: transparent;
        color: white;
        outline: none;
        border: none;
    }

    tr > th:last-of-type,
    tr > td:last-of-type {
        width: 49vw;
        display: flex; 
        flex-flow: row;
        flex-wrap: wrap; 
    }

    tr > th:not(:last-of-type),
    tr > td:not(:last-of-type) {
        width: 17vw;
    }

    td > span {
        padding: 0 .25rem;
    }

    td > span:hover {
        background-color: rgba(255, 255, 255, 0.5);
        cursor: pointer;
    }

</style>
{% endblock %}

{% block scripts-top %}
<script src="/static/xlsx.full.min.js"></script>
{% endblock %}

{% block body %}
<div class="wrapper">
    <table id="table">
        <thead>
            <tr>
                <th>Materiálové číslo</th>
                <th>Aktualizováno</th>
                <th>Skupina</th>
                <th>Nadřazené materiály</th>
            </tr>
        </thead>

        <tbody>
            {% for material, primary_materials in other_materials.items %}
            <tr>
                <td>{{material.material_number}}</td>
                <td></td>
                <td>
                    <input data-id="{{material.id}}" data-field="material-group" list="material-groups" name="material-groups"
                    value='{{material.material_group.material_group|default_if_none:""}}'>
                    <span style="display: none;">{{material.material_group.material_group|default_if_none:""}}</span>
                </td>
                <td>{% for material in primary_materials %}<span>{{material}}</span>{% endfor %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<datalist id="material-groups">
    {% for material_group in material_groups %}
    <option value="{{material_group.material_group}}"></option>
    {% endfor %}
</datalist>



{% endblock %}

{% block scripts %}
<script>

    const inputFields = document.querySelectorAll('input');


    inputFields.forEach(inputField => {
        inputField.addEventListener('blur', (e) => {
            fetch(window.location, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    'field': e.target.dataset.field,
                    'id': e.target.dataset.id,
                    'value': e.target.value,
                })
            })
        })
    })

    document.addEventListener('keydown', (e) => {
        if (String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
            let workbook = XLSX.utils.table_to_book(document.getElementById("table"));
            XLSX.writeFile(workbook, "other_materials.xlsb");
        }
    })

</script>
{% endblock %}

reman_2/templates/reman_2/recondition.html
{% extends 'reman_2/base.html' %}
{% block style %}
<style>
    div {
        color: white;
    }

    table {
        position: relative;
        top: 5vh;
        max-height: 95vh;
        width: 100vw;
        overflow: auto;
        max-width: 100%;
        border: 1px solid lightgray;
        border-collapse: collapse;
        color: white;
        font-size: small;
        /* table-layout: fixed; */
        background-color: hsla(100, 50%, 5%, .9);
        cursor: pointer;
    }

    thead {
        position: sticky;
        top: 0vh;
        background-color: black;
        width: 100vw;
        max-width: 100%;
    }
</style>
{% endblock %}

{% block scripts-top %}
<script src="/static/xlsx.full.min.js"></script>
{% endblock %}

{% block body %}

<div class="wrapper">
    <table id="table">
        <thead>
            <tr id="table-heading-row">
                <th>Vstupní materiál</th>
                <th>Výstupní materiál</th>
                <th># na vstupu</th>
                <th># na výstupu</th>
                <th>Výsledek</th>
            </tr>
        </thead>

        <tbody id="table-body">
        </tbody>
    </table>
</div>

{% endblock %}

{% block scripts %}
<script>
    const data = {{results|safe}}
    const tableBody = document.getElementById('table-body');
    const excluded = ['meta', 'level', 'as_input', 'as_output'];
    const errorCodes = new Set()

    Object.entries(data).forEach(entry => {
        Object.keys(Object.entries(entry[1])[0][1][3]).forEach(errorCode => {
            errorCodes.add(errorCode);
        })
    })

    errorCodes.forEach(errorCode => {
        let damageCodeCell = document.getElementById('table-heading-row').insertCell(-1);
        damageCodeCell.textContent = errorCode;
        damageCodeCell.dataset.damageCodeCell = errorCode;
    });

    Object.entries(data).forEach(entry => {
        processEntry(entry);
    })



    function processEntry(entry) {
        let row = tableBody.insertRow(-1);
        let sourceMaterialCell = row.insertCell(-1);
        sourceMaterialCell.textContent = entry[0];
        let entries = Object.entries(entry[1]);
        let finishedMaterialCell = row.insertCell(-1);
        finishedMaterialCell.textContent = entries[0][0];
        let sourceMaterialCountCell = row.insertCell(-1);
        sourceMaterialCountCell.textContent = entries[0][1][0];
        let finishedMaterialCountCell = row.insertCell(-1);
        finishedMaterialCountCell.textContent = entries[0][1][1];
        let resultCell = row.insertCell(-1);
        resultCell.textContent = `${(parseFloat(entries[0][1][2]) * 100).toFixed(2)}%`;
        errorCodes.forEach(() => {
            let cell = row.insertCell(-1);
            cell.textContent = "0";
        });
        let errors = entries[0][1][3];
        Object.entries(errors).forEach((errorArray) => {
            let errorCodeCellIndex = document.querySelector(`td[data-damage-code-cell="${errorArray[0]}"]`).cellIndex;
            row.getElementsByTagName('td')[errorCodeCellIndex].textContent = errorArray[1];
        })
    }

    document.addEventListener('keydown', (e) => {
        if (String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
            let workbook = XLSX.utils.table_to_book(document.getElementById("table"));
            XLSX.writeFile(workbook, "Recondition.xlsb");
        }
    })
    
</script>
{% endblock %}

reman_2/templates/reman_2/settings.html
{% extends 'reman_2/base.html' %}

{% block style %}
<style>

.settings-container {
    display: flex;
    flex-flow: row;
    flex-wrap: wrap;
}

.customers,
.material-groups,
.reporting-period {
    background-color: white;
    border: 1px solid black;
    margin: calc(5vh + 1rem) 3rem;
    max-height: 40vh;
    min-width: 40vw;
    flex-grow: 1;
    padding: 1rem 2rem;
    display: flex;
    flex-flow: column;
}

.reporting-period {
    flex-grow: 0;
}

.header {
    display: flex;
    flex-flow: row;
    justify-content: space-between;
    cursor: pointer;
}

.add-new {
    display: flex;
    justify-content: center;
    align-items: center;
    border: 1px solid rgba(0,0,0,0.25);
    width: 30px;
    height: 30px;
    border-radius: 100%;
    font-size: 30px;
}

.add-new:hover {
    background-color: rgba(0,0,0,0.05);
}

.listing {
    display: flex;
    flex-flow: column;
    overflow: auto;
}

.listing div {
    padding: 0.25rem 1rem;
}
   
</style>
{% endblock %}
{% block body %}

<div class="settings-container">

    <div class="customers" data-container>
        <div class="header">
        <h2>Zákazníci</h2>
        <div class="add-new" data-type="customer-name" onclick="addNew(this)">+</div>
    </div>
    
    <div class="listing">
        {% for customer in customers %}
        <div>{{customer.customer_name}}</div>
        {% endfor %}
    </div>
</div>

<div class="material-groups" data-container>
    <div class="header">
        <h2>Materiálové skupiny</h2>
        <div class="add-new" data-type="material-group" onclick="addNew(this)">+</div>
    </div>

    <div class="listing">
        {% for group in material_groups %}
        <div>{{group.material_group}}</div>
        {% endfor %}
    </div>
</div>

<div class="reporting-period" data-container>
    <div class="header" style="display: flex; flex-flow: column">
        <h2>Období zpracování</h2>
        <div style="padding: 0.25rem 1rem" >
            <label for="date-from">Od
                <input type="date" name="date-from" id="date-from">
            </label>
            <label for="date-to">Do
                <input type="date" name="date-to" id="date-to">
            </label>

            <input type="button" value="Nastavit" onclick="setDates()">
        </div>
    </div>
</div>

</div>
{% endblock %}

{% block scripts %}
<script>
    var sessionDateFrom = '{{date_from}}'
    var sessionDateTo = '{{date_to}}'

    window.addEventListener('DOMContentLoaded', () => { prefillDates() })

    function prefillDates() {
        if (!sessionDateFrom) {
            let dateFrom = new Date(new Date().setMonth(new Date().getMonth() - 1))
            let dateTo = new Date()
            document.getElementById('date-from').value = new Date(dateFrom.setDate(1)).toISOString().slice(0, 10) //.setDate(1).setMonth(new Date().getMonth() - 1)
            document.getElementById('date-to').value = new Date(new Date().setDate(0)).toISOString().slice(0, 10)
        } else {
            document.getElementById('date-from').value = sessionDateFrom;
            document.getElementById('date-to').value = sessionDateTo;
        }
    }

    function setDates() {
        let dateFrom = document.getElementById('date-from').value;
        let dateTo = document.getElementById('date-to').value;
        fetch(window.location, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({'dateFrom': dateFrom, 'dateTo': dateTo})
        })
    }

    function addNew(el) {
        let container = el.closest("[data-container]");
        let listing = container.querySelector('.listing');
        let newItem = document.createElement('div');
        newItem.contentEditable = true;
        newItem.dataset.type = el.dataset.type;
        listing.append(newItem);
        newItem.focus();
        newItem.addEventListener("keypress", (e) => {
            if (e.key === "Enter") {
                e.preventDefault();
                e.target.blur();
                fetch(window.location, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({'data-type': e.target.dataset.type, 'data-value': e.target.textContent})
                })
            }
        })
    }
</script>
{% endblock %}