maintenance/urls.py
from django.urls import path
from .views import index, show_parts, upload_spare_parts_list, check_if_part_exists, upload_parts, upload_parts_to_database, save_parts, add_line, remove_line, remove_parts_from_database, show_parts_from_line, delete_line, edit_columns

app_name="maintenance"

urlpatterns = [
    path('maintenance', index, name='index'),
    path('maintenance/show_parts', show_parts, name='show_parts'),
    path('maintenance/add_line', add_line, name='add_line'),
    path('maintenance/delete_line', delete_line, name='delete_line'),
    path('maintenance/remove_line', remove_line, name='remove_line'),
    path('maintenance/show_parts_from_line', show_parts_from_line, name='show_parts_from_line'),
    path('maintenance/upload_parts', upload_parts, name='upload_parts'),
    path('maintenance/upload_spare_parts_list', upload_spare_parts_list, name='upload_spare_parts_list'),
    path('maintenance/edit_columns', edit_columns, name='edit_columns'),
    path('maintenance/utils/check_if_part_exists', check_if_part_exists, name='check_if_part_exists'),
    path('maintenance/utils/upload_parts_to_database', upload_parts_to_database, name='upload_parts_to_database'),
    path('maintenance/utils/save_parts', save_parts, name='save_parts'),
    path('maintenance/utils/remove_parts_from_database', remove_parts_from_database, name='remove_parts_from_database'),
]

maintenance/models.py
from ssl import Options
from django.db import models
from django.forms import CharField
from django.contrib.auth.models import User

class Line(models.Model):
    name = models.CharField(max_length=255, unique=True)


class Part(models.Model):
    label_1 = models.CharField(max_length=255, null=True)
    label_2 = models.CharField(max_length=255, null=True)
    manufacturing_number = models.CharField(max_length=255, null=True)
    manufacturer = models.CharField(max_length=255, null=True)
    sap_number = models.CharField(max_length=255, null=True)
    part_class = models.CharField(max_length=255, null=True)
    matchcode = models.CharField(max_length=255, null=True)
    produced_part = models.BooleanField(null=True)
    electrical = models.BooleanField(null=True)
    mechanical = models.BooleanField(null=True)
    price = models.CharField(max_length=255, blank=True, null=True)
    delivery_time = models.CharField(max_length=3, null=True, blank=True)
    wearable = models.BooleanField(null=True)


class SpareParts(models.Model):
    line = models.ForeignKey(to=Line,  on_delete=models.SET_NULL, null=True)
    part = models.ForeignKey(to=Part, on_delete=models.SET_NULL, null=True)
    usage_description = models.CharField(max_length=255, null=True)
    station = models.CharField(max_length=255, null=True)
    position = models.CharField(max_length=255, null=True)
    quantity = models.CharField(max_length=255, null=True)
    documentation_label = models.CharField(max_length=255, null=True)
    safety_stock = models.CharField(max_length=16, null=True)
    criticality = models.CharField(max_length=16, null=True)
    recommended_part = models.BooleanField(null=True)


class Columns(models.Model):
    label_cz = models.CharField(max_length=255, null=True)
    label_en = models.CharField(max_length=255, null=True)
    technical_name = models.CharField(max_length=255, null=True)
    part_related = models.BooleanField()
    line_related = models.BooleanField()
    crucial = models.BooleanField()
    visible_by_default = models.BooleanField(default=False)
    is_boolean = models.BooleanField(default=False)


class UserVisible(models.Model):
    column = models.ForeignKey(to=Columns, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    visible = models.BooleanField()

maintenance/templates/add_line.html
{% extends "maintenance_base.html" %}
{% block title %}
<title>Přidání linky</title>
{% endblock %}

{% block breadcrumbs %}
<span>Přidání linky</span>
{% endblock %}

{% block body %}
<form method="post">{% csrf_token %}
    <label>Název linky</label>
    <input type="text" placeholder="Označení linky" name="line">

    <input type="submit">
</form>

{% if message %}
    {{message}}
{% endif %}
{% endblock %}

maintenance/templates/delete_line.html
{% extends "maintenance_base.html" %}
{% block title %}
<title>Smazání linky</title>
{% endblock %}

{% block breadcrumbs %}
<span>Smazání linky</span>
{% endblock %}

{% block body %}

{% for line in lines %}
    <div>
        {{line.name}} <span style="margin-left: 3rem; cursor: pointer" data-line-id="{{line.id}}"> smazat </span>
    </div>
{% endfor %}

{% endblock %}

{% block js-bottom %}
<script>
    const deleteSpans = document.querySelectorAll('span[data-line-id]')
    const url_remove_line = "{% url 'maintenance:delete_line' %}"

    deleteSpans.forEach(deleteSpan => {
        deleteSpan.addEventListener('click', (e) => {
            removeLine(e.target.dataset.lineId).then(() => e.target.parentElement.remove())
        })
    })
</script>
{% endblock %}

maintenance/templates/edit_columns.html
{% extends 'maintenance_base.html' %}

{% block breadcrumbs %}
<span>Úprava atributů</span>
{% endblock %}

{% block body %}
<table>
    <thead>
        <th>Název sloupce</th>
        <th>Klíčový</th>
        <th>Předvoleně viditelný</th>
    </thead>

    <tbody>
        {% for column in columns %}
        <tr>
            <td>{{column.label_cz}}</td>
            <td class="boolean-td"><input data-purpose="crucial" data-id="{{column.id}}" type="checkbox" name="crucial" {% if column.crucial %} checked {% endif %}></td>
            <td class="boolean-td"><input data-purpose="visible_by_default" data-id="{{column.id}}" type="checkbox" name="visible_by_defaut" {% if column.visible_by_default %} checked {% endif %}></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block js-bottom %}
<script>
    const checkboxes = document.querySelectorAll('input[type="checkbox"]')
    const edit_columns_url = "{% url 'maintenance:edit_columns' %}"

    checkboxes.forEach(checkbox => {
        checkbox.addEventListener('click', (e) => { 
            edit_columns(e.target.dataset.id, e.target.dataset.purpose, e.target.checked).then(resp => console.log(resp))
        })
    })

    async function edit_columns(column_id, purpose, checked) {
        const response = await fetch(edit_columns_url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ 'id': column_id, 'purpose': purpose, 'checked': checked })
        });
    }
</script>

{% endblock %}

maintenance/templates/edit_line_spare_parts.html
<!-- Zde bude mozne editovat dily na lince, zmena v partnumberu ho "oddeli" od standardnich dilu, vznikne novy -->

maintenance/templates/maintenance_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'maintenance.css' %}">
    <script src="{% static 'maintenance.js' %}"></script>

    {% block js-top %}
    {% endblock %}

    {% block title %}
    {% endblock %}
</head>
<body>
    <div class="header">
        <div class="breadcrumbs">
            <span><a href="{% url 'maintenance:index' %}">Domů</a> > </span>
            {% block breadcrumbs %}
            {% endblock %}
        </div>

        <div class="login">
            {% if user.is_authenticated %}<span>{{user.first_name}} {{user.last_name}}</span><span> <a href="{% url 'logout' %}?next={{request.path}}">(odhlásit)</a></span>
            {% else %}<span><a href="{% url 'login' %}?next={{request.path}}">Přihlášení</a></span>
            {% endif %}
        </div>
    </div>

    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
    
</body>

    {% block js-bottom %}
    {% endblock %}
</html>

maintenance/templates/maintenance_index.html
{% extends "maintenance_base.html" %}
{% block title %}
<title>Domov</title>
{% endblock %}

{% block body %}

<ul>
    <li>Díly (master data)
        <ul>
            <li><a href="{% url 'maintenance:show_parts' %}">Zobrazení/Úprava seznamu dílů</a></li>
            <li><a href="{% url 'maintenance:upload_parts' %}">Nahrání seznamu dílů</a></li>
        </ul>
    </li>

    <hr>

    <li>Díly (linky)
        <ul>
            <li><a href="{% url 'maintenance:show_parts_from_line' %}">Zobrazení/Úprava seznamu dílu z linky</a> {% for line in lines %} (<a href="{% url 'maintenance:show_parts_from_line' %}?line={{line.name}}">{{line.name}}</a>) {% endfor %}</li>
            <li><a href="{% url 'maintenance:upload_spare_parts_list' %}">Nahrání seznamu dílu z linky</a></li>
        </ul>
    </li>

    <hr>
    
    <li>Linky
        <ul>
            <li><a href="{% url 'maintenance:add_line' %}">Přidat linku</a></li>
            <li><a href="{% url 'maintenance:delete_line' %}">Smazat linku</a></li>
        </ul>
    </li>
    
    <hr>
    
    <li>Nastavení
        <ul>
            <li><a href="{% url 'maintenance:edit_columns' %}">Úprava atributů</a></li>
        </ul>
    </li>
</ul>

{% endblock %}

maintenance/templates/show_parts.html
{% extends "maintenance_base.html" %}
{% block title %}
<title>Úprava dílů</title>
{% endblock %}


{% block js-top %}
<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
{% endblock %}
{% load maintenance_extras %}

{% block breadcrumbs %}
<span>Úprava dílů</span>
{% endblock %}


{% block body %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<form action="POST">
    <fieldset>
        <legend>Zobrazované sloupce</legend>
        <div style="display: grid; grid-column-gap: 12%; grid-template-columns: 1fr 1fr 1fr 1fr 1fr;">
            {% for c in columns %}
            <div style="display: flex; flex-flow: row; justify-content: space-between;">
                <label>{{c.label_cz}}</label>
                <input type="checkbox" data-column-name-filter="{{c.technical_name}}" {% visible_for_user c %} {% if c.visible_by_default %} disabled {% endif %}>
            </div>
            {% endfor %}
        </div>
    </fieldset>
</form>

<table class="spare-parts-table" id="spare-parts-table">
    <caption>
        <input type="button" id="remove-rows-button" value="Odstranit vybrané řádky" class="not-displayed">
        <input type="button" id="upload-list" value="Uložit změny" class="not-displayed">
    </caption>
    <div class="search_body">
        <div class="search-container">
            <input type="text" id="search" name="search" onkeyup="search()" placeholder="Vyhledávání" class="search-input">
            <i class="fa fa-search" aria-hidden="true"></i>
        </div>
    </div>
    <thead id="table-head">
        <tr id="table-header-tr">
            {% for c in user_columns %}
                <th data-column-technical-name="{{c.technical_name}}" onclick="sortBy(this)" class="both sorting" id="{{c.technical_name}}">{{c.label_cz}}</th>
            {% endfor %}
            {% for line in lines %}
                <th>{{line}}</th>
            {% endfor %}
        </tr>

    <tbody id="table-body">
        {% for part in parts %}
            <tr data-part-id = "{{part.id}}" data-to-remove="false" data-type="part" data-line="no-line">
                {% for c in user_columns %}
                    {% if not c.is_boolean %}
                        <td data-purpose="{{ c.technical_name }}" data-original-value="{% get_attribute part c.technical_name %}" contenteditable="true">{% get_attribute part c.technical_name %}</td>
                    {% else %}
                        {% get_attribute part c.technical_name true as bool %}
                        <td class="table-cell-centered" data-purpose="{{ c.technical_name }}" data-original-value="{{bool}}"><input type="checkbox" {% if bool == "true" or bool == "True" or bool == True %} checked {% endif %}></td>
                    {% endif %}
                {% endfor %}
                
                
                {% for line in lines %}
                <td style="text-align: center";>
                    {% for sparepart in part.spareparts_set.all %}
                        {% if sparepart.line.name == line %}
                            <input type="checkbox" checked disabled><span style="display: none">{{line}}</span>
                        {% endif %}
                    {% endfor %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block js-bottom %}
<script>
    window.addEventListener('DOMContentLoaded', (event) => { addIndexColumn() });    
    const tableHeader = document.getElementById("table-header-tr");
    const tableHead = document.getElementById("table-head");
    const tableBody = document.getElementById("table-body");
    const removeRowsButton = document.getElementById("remove-rows-button");
    const saveButton = document.getElementById("upload-list");
    const visibleColumnOptions = document.querySelectorAll('input[type="checkbox"]:not(:disabled)');
    removeRowsButton.addEventListener('click', removeParts);
    saveButton.addEventListener('click', callSaveParts);
    const url_save_parts = "{% url 'maintenance:save_parts' %}"
    const url_show_parts = "{% url 'maintenance:show_parts' %}"
    const url_remove_parts_from_database = "{% url 'maintenance:remove_parts_from_database' %}"
    var editedCellsCount = 0;
    var editedParts = {}
    var changedRowsData = {};
    var partId;

    visibleColumnOptions.forEach(option => {
        option.addEventListener('input', (e) => {
            visibleColumnsChanged(e.target.dataset.columnNameFilter, "{{request.user.username}}", e.target.checked).then(() => location.reload());
        })
    })

    const contentCells = document.querySelectorAll("[data-purpose]")

    contentCells.forEach(contentCell => {
        contentCell.addEventListener('input', (e) => {
            
            if (e.target.tagName == "INPUT") {
                partId = e.target.parentElement.parentElement.dataset.partId;    
            } else {
                partId = e.target.parentElement.dataset.partId;
            }

            if (partId in editedParts == false) {
                editedParts[partId] = 0
            }

            switch (e.target.tagName) {
                case "INPUT":
                    let originalStateInput = e.target.parentElement.dataset.originalValue.toLowerCase() == "false" ? false : true;
                    let currentStateInput = e.target.checked;
                    if (originalStateInput != currentStateInput) {
                        editedCellsCount += 1;
                        editedParts[partId] += 1;
                    } else {
                        editedCellsCount -= 1;
                        editedParts[partId] -= 1;
                    }
                    e.target.parentElement.dataset.currentValue = `${currentStateInput}`;
                    break;

                case "TD":
                    let previousState = e.target.dataset.originalValue;
                    let currentState = e.target.textContent;
                    if (previousState != currentState) {
                        editedCellsCount += 1;
                        editedParts[partId] += 1;
                    } else {
                        editedCellsCount -= 1;
                        editedParts[partId] -= 1;
                    }
                    e.target.dataset.currentValue = currentState;
                    break;
            }

            if (editedCellsCount > 0) {
                saveButton.classList.remove("not-displayed");
            } else {
                saveButton.classList.add("not-displayed");
            }
        })
    })

    document.addEventListener('keydown', (e) => {
        if (e.ctrlKey && String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
            let table_elt = document.getElementById("spare-parts-table");
            let workbook = XLSX.utils.table_to_book(table_elt);
            XLSX.writeFile(workbook, "Report.xlsb");
        }
    })
    

</script>


{% endblock %}

maintenance/templates/show_parts_from_line.html
{% extends "maintenance_base.html" %}
{% block title %}
<title>Úprava dílů</title>
{% endblock %}

{% load maintenance_extras %}

{% block js-top %}
<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
{% endblock %}

{% block breadcrumbs %}
<span>Úprava dílů {% if not line %} (z linek) {% else %} (z linky {{line.name}}) {% endif %}</span>
{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<form action="POST">
    <fieldset>
        <legend>Zobrazované sloupce</legend>
        <div style="display: grid; grid-column-gap: 12%; grid-template-columns: 1fr 1fr 1fr 1fr 1fr;">
            {% for c in columns %}
            <div style="display: flex; flex-flow: row; justify-content: space-between;">
                <label>{{c.label_cz}}</label>
                <input type="checkbox" data-column-name-filter="{{c.technical_name}}" {% visible_for_user c %} {% if c.visible_by_default %} disabled {% endif %}>
            </div>
            {% endfor %}
        </div>
    </fieldset>
</form>

<table class="spare-parts-table" id="spare-parts-table">
    <caption>
        <input type="button" id="remove-rows-button" value="Odstranit vybrané řádky" class="not-displayed">
        <input type="button" id="upload-list" value="Uložit změny" class="not-displayed">
    </caption>
    <div class="search_body">
        <div class="search-container">
            <input type="text" id="search" name="search" onkeyup="search()" placeholder="Vyhledávání" class="search-input">
            <i class="fa fa-search" aria-hidden="true"></i>
        </div>
    </div>
    <thead id="table-head">
        <tr id="table-header-tr">
            {% for c in user_columns %}
            <th data-column-technical-name="{{c.technical_name}}" onclick="sortBy(this)" class="both sorting"
                id="{{c.technical_name}}">{{c.label_cz}}</th>
            {% endfor %}
            {% for line in lines %}
            <th>{{line}}</th>
            {% endfor %}
        </tr>

    <tbody id="table-body">
        {% for part in spare_parts %}
        <tr data-part-id="{{part.part.id}}" data-to-remove="false" data-type="spare-part" data-line="{{line.name}}">
            {% for c in user_columns %}
            {% if not c.is_boolean %}
            <td data-purpose="{{ c.technical_name }}" data-original-value="{% get_attribute part c.technical_name %}"
                contenteditable="true">{% get_attribute part c.technical_name %}</td>
            {% else %}
            {% get_attribute part c.technical_name true as bool %}
            <td class="table-cell-centered" data-purpose="{{ c.technical_name }}" data-original-value="{{bool}}"><input type="checkbox"></td>
            {% endif %}
            {% endfor %}


            {% for line in lines %}
            <td>
                {% for sparepart in part.spareparts_set.all %}
                {% if sparepart.line.name == line %}
                {{sparepart.quantity}}
                {% endif %}
                {% endfor %}

            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block js-bottom %}
<script>
    window.addEventListener('DOMContentLoaded', (event) => { addIndexColumn() });
    const tableHeader = document.getElementById("table-header-tr");
    const tableHead = document.getElementById("table-head");
    const tableBody = document.getElementById("table-body");
    const removeRowsButton = document.getElementById("remove-rows-button");
    const saveButton = document.getElementById("upload-list");
    const visibleColumnOptions = document.querySelectorAll('input[type="checkbox"]:not(:disabled)');
    removeRowsButton.addEventListener('click', removeParts);
    saveButton.addEventListener('click', callSaveParts);
    const url_save_parts = "{% url 'maintenance:save_parts' %}"
    const url_show_parts = "{% url 'maintenance:show_parts' %}"
    const url_remove_parts_from_database = "{% url 'maintenance:remove_parts_from_database' %}"
    var editedCellsCount = 0;
    var editedParts = {}
    var changedRowsData = {};
    var partId;

    visibleColumnOptions.forEach(option => {
        option.addEventListener('input', (e) => {
            visibleColumnsChanged(e.target.dataset.columnNameFilter, "{{request.user.username}}", e.target.checked).then(() => location.reload());
        })
    })

    const contentCells = document.querySelectorAll("[data-purpose]")

    contentCells.forEach(contentCell => {
        contentCell.addEventListener('input', (e) => {

            if (e.target.tagName == "INPUT") {
                partId = e.target.parentElement.parentElement.dataset.partId;
            } else {
                partId = e.target.parentElement.dataset.partId;
            }

            if (partId in editedParts == false) {
                editedParts[partId] = 0
            }

            switch (e.target.tagName) {
                case "INPUT":
                    let originalStateInput = e.target.parentElement.dataset.originalValue.toLowerCase() == "false" ? false : true;
                    let currentStateInput = e.target.checked;
                    if (originalStateInput != currentStateInput) {
                        editedCellsCount += 1;
                        editedParts[partId] += 1;
                    } else {
                        editedCellsCount -= 1;
                        editedParts[partId] -= 1;
                    }
                    e.target.parentElement.dataset.currentValue = `${currentStateInput}`;
                    break;

                case "TD":
                    let previousState = e.target.dataset.originalValue;
                    let currentState = e.target.textContent;
                    if (previousState != currentState) {
                        editedCellsCount += 1;
                        editedParts[partId] += 1;
                    } else {
                        editedCellsCount -= 1;
                        editedParts[partId] -= 1;
                    }
                    e.target.dataset.currentValue = currentState;
                    break;
            }

            if (editedCellsCount > 0) {
                saveButton.classList.remove("not-displayed");
            } else {
                saveButton.classList.add("not-displayed");
            }
        })
    })
    document.addEventListener('keydown', (e) => {
        if (e.ctrlKey && String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
            let table_elt = document.getElementById("spare-parts-table");
            let workbook = XLSX.utils.table_to_book(table_elt);
            XLSX.writeFile(workbook, "Report.xlsb");
        }
    })

    document.addEventListener('keydown', (e) => {
            if (e.ctrlKey && String.fromCharCode(e.keyCode).toLowerCase() === 'x') {
                let table_elt = document.getElementById("spare-parts-table");
                let workbook = XLSX.utils.table_to_book(table_elt);
                XLSX.writeFile(workbook, "Report.xlsb");
            }
        })
</script>


{% endblock %}

maintenance/templates/upload_parts.html
{% extends "maintenance_base.html" %}
{% block title %}
    <title>Nahrání dílů</title>
{% endblock %}

{% load maintenance_extras %}

{% block js-top %}
<script src="https://unpkg.com/xlsx@0.18.0/jszip.js"></script>
<script src="https://unpkg.com/xlsx@0.18.0/xlsx.js"></script>
{% endblock %}

{% block breadcrumbs %}
<span>Nahrání dílů</span>
{% endblock %}


{% block body %}
<form enctype="multipart/form-data">
    <input id="upload" type=file name="files[]">
</form>

<table class="spare-parts-table">
    <caption>
        <div><span>Povinné sloupce:</span> {{ crucial_columns|get_label_cz|join:", " }} </div>
        <div><span>Volitelné sloupce:</span>{{ part_related_columns|get_label_cz|join:", " }}</div>
        <input type="button" id="remove-rows-button" value="Odstranit vybrané řádky" class="not-displayed">
        <input type="button" id="show-existing-button" value="Zvýraznit existující díly" class="not-displayed">
        <input type="button" id="upload-list" value="Odeslat seznam dílů" class="not-displayed">
    </caption>

    <thead id="table-head">
        <tr id="table-header-tr">
        </tr>
    </thead>

    <tbody id="table-body">    
    </tbody>
</table>
{% endblock %}

{% block js-bottom %}
<script>
    document.getElementById('upload').addEventListener('change', handleFileSelect, false);
    const tableHeader = document.getElementById("table-header-tr");
    const tableHead = document.getElementById("table-head");
    const startingIndex = 0;
    const tableBody = document.getElementById("table-body");
    const removeRowsButton = document.getElementById("remove-rows-button");
    const showExistingButton = document.getElementById("show-existing-button");
    const uploadPartsButton = document.getElementById("upload-list");
    removeRowsButton.addEventListener('click', removeRows);
    showExistingButton.addEventListener('click', highlightExisting);
    uploadPartsButton.addEventListener('click', uploadParts);
    const url = "{% url 'maintenance:check_if_part_exists' %}"
    const url_upload_parts = "{% url 'maintenance:upload_parts_to_database' %}"
    const columnsOptions = {{columns_options|safe}};
    const crucialColumns = {{crucial_columns|get_label_cz|safe}};
</script>


{% endblock %}

maintenance/templates/upload_spare_parts_list.html
{% extends "maintenance_base.html" %}
{% block title %}
    <title>Nahrání seznamu dílů</title>
{% endblock %}

{% load maintenance_extras %}

{% block js-top %}
    <script src="https://unpkg.com/xlsx@0.18.0/jszip.js"></script>
    <script src="https://unpkg.com/xlsx@0.18.0/xlsx.js"></script>
{% endblock %}

{% block breadcrumbs %}
<span>Nahrání dílů (linka)</span>
{% endblock %}

{% block body %}
    <form enctype="multipart/form-data">
        <input id="upload" type=file name="files[]">
        <label>Linka</label>
        <select id="selected-line">
            <option selected></option>
            {% for line in lines %}
            <option value="{{line}}">{{line}}</option>
            {% endfor %}
        </select>
    </form>

        <table class="spare-parts-table">
            <caption>
                <div><span>Povinné sloupce:</span> {{ crucial_columns|get_label_cz|join:", " }} </div>
                <div><span>Volitelné sloupce:</span>{{ other_columns|get_label_cz|join:", " }}</div>
                <input type="button" id="remove-rows-button" value="Odstranit vybrané řádky" class="not-displayed">
                <input type="button" id="show-existing-button" value="Zvýraznit existující díly" class="not-displayed">
                <input type="button" id="upload-list" value="Odeslat seznam dílů" class="not-displayed">
            </caption>
            <thead id="table-head">
                <!-- <tr id="table-header-tr">
                </tr> -->
            </thead>

            <tbody id="table-body">
            </tbody>
        </table>
{% endblock %}

{% block js-bottom %}
<script>
    document.getElementById('upload').addEventListener('change', handleFileSelect, false);
    // const tableHeader = document.getElementById("table-header-tr");
    const tableHead = document.getElementById("table-head");
    const tableBody = document.getElementById("table-body");
    const startingIndex = -1;
    const removeRowsButton = document.getElementById("remove-rows-button");
    const showExistingButton = document.getElementById("show-existing-button");
    const uploadPartsButton = document.getElementById("upload-list");
    const linesSelect = document.getElementById("selected-line");
    removeRowsButton.addEventListener('click', removeRows);
    showExistingButton.addEventListener('click', highlightExisting);
    uploadPartsButton.addEventListener('click', uploadParts);
    const url = "{% url 'maintenance:check_if_part_exists' %}"
    const url_upload_parts = "{% url 'maintenance:upload_parts_to_database' %}"
    const columnsOptions = {{columns_options|safe}};
    const crucialColumns = {{crucial_columns|get_label_cz|safe}};
</script>


{% endblock %}