logistics/urls.py
from django.urls import path
from .views import get_sum_for_report_detail, index, enter_logistics_downtime, send_email_daily_frontend, visualization, upload_excel, show_downtimes, edit_downtime, definitions, profile, train_circuit, get_downtime_details, fetch_external_downtimes, fill_in_shifts, get_sum_for_report, get_sum_for_report_detail

app_name = "logistics"

urlpatterns = [
    path('logistics', index, name='index'),
    path('logistics/enter_logistics_downtime', enter_logistics_downtime, name='enter_logistics_downtime'),
    path('logistics/visualization', visualization, name='visualization'),
    path('logistics/upload_excel', upload_excel, name='upload_excel'),
    path('logistics/show_downtimes', show_downtimes, name='show_downtimes'),
    path('logistics/edit_downtime', edit_downtime, name='edit_downtime'),
    path('logistics/definitions', definitions, name='definitions'),
    path('logistics/profile/<str:user_full_name>', profile, name='profile'),
    path('logistics/train_circuit/<int:train_circuit_number>/<str:line_name>', train_circuit, name='train_circuit'),
    path('logistics/get_downtime_details', get_downtime_details, name='get_downtime_details'),
    path('logistics/fetch_external_downtimes', fetch_external_downtimes, name='fetch_external_downtimes'),
    path('logistics/fill_in_shifts', fill_in_shifts, name='fill_in_shifts'),
    path('logistics/get_sum_for_report', get_sum_for_report, name='get_sum_for_report'),
    path('logistics/get_sum_for_report_detail', get_sum_for_report_detail, name='get_sum_for_report_detail'),
    path('logistics/send_email_daily', send_email_daily_frontend, name='send_email_daily')
]

logistics/templates/done.html
{% extends 'logistics_base.html' %}


{% block body %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<nav style="width: 100%"> 
    <ul>
        <a href="{% url 'logistics:enter_logistics_downtime' %}"><li>Zadání prostoje</li></a>
        <a href="{% url 'logistics:upload_excel' %}"><li>Nahrání prostojů z Excelu</li></a>
        <a href="{% url 'logistics:enter_logistics_downtime' %}"><li>Přehledy prostojů</li></a>
        <a href="{% url 'logistics:visualization' %}"><li>Vizualizace</li></a>
        <a href="{% url 'logistics:enter_logistics_downtime' %}"><li>Definice</li></a>
    </ul>
</nav>
{% endblock %}
<body>
    <div class="row g-3">
        <div class="col-md-3 position-relative">
            <label class="form-label">Dokončeno</label>
        </div>
    </div>
</body>

logistics/templates/logistics_base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'logistics.js' %}"></script>
    <link rel="stylesheet" href="{% static 'logistics.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="{% static 'kbfav.ico' %}">
    {% block title %}
    <title>Logistika</title>
    {% endblock %}

    {% block js-top %}
    {% endblock %}
</head>
<body>
    <div class="header">
        <div class="breadcrumbs">
            <span><a href="{% url 'logistics:index' %}">Domů</a> > </span>
            {% block breadcrumbs %}
            {% endblock %}
        </div>
    
        <div class="login">
            {% if user.is_authenticated %}<span><a href="{% url 'logistics:profile' user.last_name %}, {{user.first_name}}">{{user.first_name}} {{user.last_name}}</a></span><span> <a
                    href="{% url 'logout' %}?next={{request.path}}">(odhlásit)</a></span>
            {% else %}<span><a href="{% url 'login' %}?next={{request.path}}">Přihlášení</a></span>
            {% endif %}
        </div>
    </div>
    
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    {% block js-bottom %}
    {% endblock %}
</body>
</html>

logistics/templates/logistics_index.html
{% extends 'logistics_base.html' %}


{% block body %}
<nav style="width: 100%"> 
    <ul>
        <a href="{% url 'logistics:enter_logistics_downtime' %}"><li>Zadání prostoje</li></a>
        <a href="{% url 'logistics:upload_excel' %}"><li>Nahrání prostojů z Excelu</li></a>
        <a href="{% url 'logistics:show_downtimes' %}"><li>Přehledy prostojů</li></a>
        <a href="{% url 'logistics:visualization' %}"><li>Vizualizace</li></a>
        <a href="{% url 'logistics:definitions' %}"><li>Definice</li></a>
    </ul>
</nav>
{% endblock %}

logistics/templates/show_downtimes.html
{% extends 'logistics_base.html' %}

{% block breadcrumbs %}
<span>Přehled prostojů</span>
{% endblock %}

{% block js-top %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock %}

{% block body %}
<style>
    .container{
        padding-right: 0%;
        padding-left: 0%;
        max-width: 100vw;
    }
    .asc::after {
        content: "▼";
        color: green;
    }

    .des::after {
        content: "▲";
        color: green;
    }

    .both::after {
        content: "▲▼";
        color: green;
    }

    .search-container{
        background: #fff;
        height: 10px;
        border-radius: 20px;
        padding: 10px 20px;
        display: flex;
        justify-content: center;
        align-items: center;
        cursor: pointer;
        transition: 0.8s;
    }

    .search-container:hover > .search-input{
        width: 400px;
    }

    .search-container .search-input{
        background: transparent;
        border: none;
        outline:none;
        width: 0px;
        font-weight: 500;
        font-size: 12px;
        transition: 0.8s;

    }

    .search-container .search-btn .fas{
        color: #808080;
    }

    .search_body {
        margin: 0;
        padding: 0;
        background-color: rgba(128,128,128,0.5);
        height: 4vh;
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
<div class="search_body">
    <div class="search-container">
        <input type="text" id="search" name="search" onkeyup="search()" placeholder="Vyhledávání" class="search-input">
        <i class="fa fa-search" aria-hidden="true"></i>
    </div>
</div>
<table class="table table-hover" id="table-to-picture">
    <thead id="table-head">
        <tr>
            <th onclick="sortBy(this)" class="both sorting" id="id">Id</th>
            <th onclick="sortBy(this)" class="both sorting" id="production-area">Výrobní oblast</th>
            <th onclick="sortBy(this)" class="both sorting" id="line">Linka</th>
            <th onclick="sortBy(this)" class="both sorting" id="downtime-start">Začátek prostoje</th>
            <th onclick="sortBy(this)" class="both sorting" id="downtime-end">Konec prostoje</th>
            <th onclick="sortBy(this)" class="both sorting" id="shift">S</th>
            <th onclick="sortBy(this)" class="both sorting" id="recorded-by">Zaznamenal</th>
            <th onclick="sortBy(this)" class="both sorting" id="duration">Trvání</th>
            <th onclick="sortBy(this)" class="both sorting" id="category-production">Kategorie (výroba)</th>
            <th onclick="sortBy(this)" class="both sorting" id="subcategory-production">Podkategorie (výroba)</th>
            <th onclick="sortBy(this)" class="both sorting" id="notes-production">Poznámky (výroba)</th>
            <th onclick="sortBy(this)" class="both sorting" id="category-logistic">Kategorie (logistika)</th>
            <th onclick="sortBy(this)" class="both sorting" id="subcategory-logistic">Podkategorie (logistika)</th>
            <th onclick="sortBy(this)" class="both sorting" id="notes-logistics">Poznámky (logistika)</th>
            <th onclick="sortBy(this)" class="both sorting" id="decoded-by">Rozklíčoval</th>
        </tr>
    </thead>

    <tbody id="table-body">
        {% for downtime in downtimes %}
        <tr data-id="{{downtime.id}}" class="visible">
            <td>{{downtime.id}}</td>
            <td>{{downtime.production_area.name}}</td>
            <td>{{downtime.line.name}}</td>
            <td>{{downtime.downtime_start|date:"d.m.Y H:i"}}</td>
            <td>{{downtime.downtime_end|date:"d.m.Y H:i"}}</td>
            <td>{{downtime.shift}}</td>
            <td>{{downtime.recorded_by}}</td>
            <td>{{downtime.duration|slice:"5"}}</td>
            <td>{{downtime.category_by_production.category}}</td>
            <td>{{downtime.subcategory_by_production.subcategory}}</td>
            <td>{{downtime.note_by_production}}</td>
            <td>{{downtime.category_by_logistics.category}}</td>
            <td>{{downtime.subcategory_by_logistics.subcategory}}</td>
            <td>{{downtime.note_by_logistics}}</td>
            <td>{{downtime.decoded_by|default_if_none:""}}</td>
        </tr>
        {% endfor %}

        {% for downtime in fp09_downtimes %}
        <tr data-id="{{downtime.id}}" class="visible">
            <td>{{downtime.id}}</td>
            <td>FP</td>
            <td>FP09</td>
            <td>{{downtime.beginning_t|date:"d.m.Y H:i"}}</td>
            <td>{{downtime.end_t|date:"d.m.Y H:i"}}</td>
            <td>{{downtime.downtime}}</td>
            <td>{{downtime.comment|default_if_none:""}}</td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}


    </tbody>
</table>

{% endblock %}

{% block js-bottom %}
<script>
    const editDowntimeUrl = "{% url 'logistics:edit_downtime' %}"
    const tableRows = document.querySelectorAll('tbody > tr');
    tableRows.forEach(tableRow => {
        tableRow.addEventListener('click', (event) => {
            let downtime_id = event.target.parentElement.dataset.id
            window.open(`${editDowntimeUrl}?downtime_id=${downtime_id}`, "Upravit prostoj")

        })
    })
    const tableHead = document.getElementById("table-head");
    const tableBody = document.getElementById("table-body");
    
function search() {
  const input = document.getElementById("search");
  const inputStr = input.value.toUpperCase();
  var even = 0
  for (var i = 0, row; row=tableBody.rows[i]; i++){
    var RowDisplay = "Hide"  
    for (var j = 0, column; column=row.cells[j]; j++){
        if (column.innerHTML.toUpperCase().includes(inputStr)){
            RowDisplay = "Show"
        }
    }
    
    if (RowDisplay == "Show"){
        row.style.display = ""
        if (row.classList.contains("visible")){

        }
        else {row.classList.add("visible")}
        if (even == 1){
        row.style.backgroundColor = "rgba(0,0,0,0.05)";
        even = 0
        }
        else {
        row.style.backgroundColor = "inherit";
        even = 1
        }
    }
    else {
        row.style.display = "none"
        row.classList.remove("visible")
    }    
  }
}
cPrev = -1; 
var charMapL = " aábcčdďeéěfghiíjklmnňoópqrřsštťuúůvwxyýzž";
var charMapU = " AÁBCČDĎEÉĚFGHIÍJKLMNŇOÓPQRŘSŠTŤUÚŮVWXYÝZŽ";
var charsOrder = {};
for(var i in charMapL.split('')) {
    charsOrder[charMapL[i]] = parseInt(i);
    charsOrder[charMapU[i]] = parseInt(i);
}

function sortBy(column){
    if (column.classList.contains("both")){
        column.classList.remove("both")
        column.classList.add("asc")
        var reverse = 0
    }
    else if (column.classList.contains("asc")){
        column.classList.add("des")
        column.classList.remove("asc")
        var reverse = 1
    }
    else {
        column.classList.add("asc")
        column.classList.remove("des")
        var reverse = 0
    }
    sortingColumns = tableHead.getElementsByClassName('sorting')
    for(var i=0; i < sortingColumns.length; i++){
        if(sortingColumns[i].id != column.id){
            if(sortingColumns[i].classList.contains("asc")){
                sortingColumns[i].classList.remove("asc")
            }
            if(sortingColumns[i].classList.contains("des")){
                sortingColumns[i].classList.remove("des")
            }
            if(sortingColumns[i].classList.contains("both")){
            }
            else{sortingColumns[i].classList.add("both")}
        }
        else{c = i}

    }
    var arrOfHiddenRows = []
    for(var i = 0, row; row=tableBody.rows[i]; i++){
        if (row.style.display == "none"){
            row.removeAttribute("style")
            arrOfHiddenRows.push(row.cells[0].innerHTML)
        }
    }
    rows = document.getElementById("table-body").rows.length;
    columns = document.getElementById("table-body").rows[0].cells.length; 
    arrTable = [...Array(rows)].map(e => Array(columns)); 
    for (ro=0; ro<rows; ro++) { 
        for (co=0; co<columns; co++) { 
            arrTable[ro][co] = document.getElementById("table-body").rows[ro].cells[co].innerHTML;
        }
    }
    columnFromArray = getCol(arrTable, c)
    columnFromArray.sort();
    columnFromArray.sort(mySort);
    rowsUsed = []
    arrTableSorted = [...Array(rows)].map(e => Array(columns))
    for (ro=0; ro<rows; ro++) {
        for (var i=0; i < columnFromArray.length; i++){
            if (columnFromArray[i] == arrTable[ro][c]){
                if(!rowsUsed.includes(i)){
                    arrTableSorted[i] = arrTable[ro]
                    rowsUsed.push(i)
                    break

                }
            }
        }
    }

    if (reverse == 1){
        arrTableSorted.reverse()
    }
    for (ro=0; ro<rows; ro++) {
        for (co=0; co<columns; co++) {
            document.getElementById("table-body").rows[ro].cells[co].innerHTML = arrTableSorted[ro][co];
        }
    }
    
    even = 0
    for(var i = 0, row; row=tableBody.rows[i]; i++){
        if (arrOfHiddenRows.includes(row.cells[0].innerHTML)){
            row.style.display = "none";
        }
        else {
            if (even == 1){
            row.style.backgroundColor = "rgba(0,0,0,0.05)";
            even = 0
            }
            else {
            row.style.backgroundColor = "inherit";
            even = 1
            }
        }
    }
 }

 function mySort(s1, s2) {
    var idx = 0;
    while ( (idx < s1.length) && (idx < s2.length) && (charsOrder[s1[idx]] == charsOrder[s2[idx]])) {
        idx ++;
    }
    if (idx == s1.length) return 1;
    if (idx == s2.length) return -1;
    return charsOrder[s1[idx]] > charsOrder[s2[idx]] ? 1 : (charsOrder[s1[idx]] < charsOrder[s2[idx]] ? -1 : 0);
}


function getCol(matrix, col) {
       var column = [];
       for(var i=0; i<matrix.length; i++){
          column.push(matrix[i][col]);
       }
       return column;
}

</script>
{% endblock %}

logistics/templates/train_circuit.html
{% extends 'logistics_base.html' %}

{% block breadcrumbs %}
<span><a href="{% url 'logistics:definitions' %}">Definice</a></span> > <span>Vlakový okruh</span>
{% endblock %}

{% load logistics_extras %}

{% block js-top %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<style>
    .btn {
        color: white;
        background-color: #7a5195;
    }

    .btn-group {
        width: 40%;
    }
</style>

{% endblock %}

{% block body %}


<h1>Vlakový okruh pro linku {{line.name}}</h1>
<form class="row g-3" method="post">{% csrf_token %}
    <div class="col-md-3 position-relative">
        <label>Číslo okruhu</label>
        <select class="form-select" id="train_circuit" name="train_circuit">
            {% for train_circuit in train_circuits %}
                <option value="{{train_circuit.number}}" {% if train_circuit.number == train_circuit_number %} selected {% endif %}>{{train_circuit.number}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="col-md-12 position-relative" style="text-align: center;">
        <div class="btn-group">
            <button type="submit" class="btn">Ok</button>
        </div>
    </div>

</form>

{% endblock %}

logistics/templates/upload_excel.html
{% extends 'logistics_base.html' %}
{% load static %}

{% block breadcrumbs %}
<span>Zadání prostoje</span>
{% endblock %}

{% block body %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<style>
    .btn {
        color: white;
        background-color: #7a5195;
        }
    .btn-group{
        width: 70%;
        margin-top: 10vh;
    }
</style>
<body>
    <form enctype="multipart/form-data" action="/logistics/upload_excel" class="row g-3" method="post">{% csrf_token %}
        <div class="col-md-3 position-relative">
        </div>
        <div class="col-md-3 position-relative">
            <img src="{% static 'microsoft-excel.png' %}" alt="excel" height="200vh">
            <label for="excel_upload" class="form-label">Nahrání Excelu</label>
            <input class="form-control" type="file" name="file" id="file" accept=".xlsx">
        </div>
        <div class="col-md-3 position-relative" style="text-align: center;">
            <div class="btn-group">
                <button type="submit" class="btn">Ok</button>
            </div>
        </div>
    </form>
</body>
{% endblock %}

logistics/templates/visualization.html
{% extends 'logistics_base.html' %}

{% block breadcrumbs %}
<span>Vizualizace prostojů</span>
{% endblock %}

{% block body %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<style>
        .All {background-color: #01263a;}
        .Obaly {background-color: #043959;}
        .Planovani {background-color: #0a4b78;}
        .System {background-color: #135e96;}
        .Zamestnanci {background-color: #2271b1;}
        .Technika {background-color: #3582c4;}
        .Vyroba {background-color: #787c82;}
        .Kvalita {background-color: #646970;}
        .Procesy {background-color: #50575e;}
        .Komunikace {background-color: #3c434a;}
        .Jine {background-color: #2c3338;}
        .btn {color: white;}
</style>
<body>
    <form class="row g-3" method="post">
        <div class="col-md-6 position-relative">
            <label for="DateFrom" class="form-label">Datum OD</label>
            <input class="form-select" type="date" id="DateFrom" name="DateFrom">
        </div>
        <div class="col-md-6 position-relative">
            <label for="DateTo" class="form-label">Datum DO</label>
            <input class="form-select" type="date" id="DateTo" name="DateTo">
        </div>
    </form>

    <div class="col-md-12 position-relative" style="text-align: center;">
        <div class="btn-group">
            <button type="button" class="btn All" onclick=SelectButton(this)>Vše</button>
            <button type="button" class="btn Obaly" onclick=SelectButton(this)>Obaly</button>
            <button type="button" class="btn Planovani" onclick=SelectButton(this)>Plánování</button>
            <button type="button" class="btn System" onclick=SelectButton(this)>Systém</button>
            <button type="button" class="btn Zamestnanci" onclick=SelectButton(this)>Zaměstnanci</button>
            <button type="button" class="btn Technika" onclick=SelectButton(this)>Technika</button>
            <button type="button" class="btn Vyroba" onclick=SelectButton(this)>Výroba</button>
            <button type="button" class="btn Kvalita" onclick=SelectButton(this)>Kvalita</button>
            <button type="button" class="btn Procesy" onclick=SelectButton(this)>Procesy</button>
            <button type="button" class="btn Komunikace" onclick=SelectButton(this)>Komunikace</button>
            <button type="button" class="btn Jine" onclick=SelectButton(this)>Jiné</button>
        </div>
    </div>
    <div class="container" style="text-align: center;">
        <div class="row">
            <div class="col">
                <div id="first_interval_chart_div">
                    <canvas id="first_interval_chart" width="300" height="400"></canvas>
                </div>
            </div>
            <div class="col">
                <div id="second_interval_chart_div">
                    <canvas id="second_interval_chart" width="300" height="400"></canvas>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="bar_chart_div">
                <canvas id="bar_chart" width="500" height="400"></canvas>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
</body>
<script>
    let now_date = new Date();
    let first_interval_start = new Date(now_date.getFullYear(), now_date.getMonth(), now_date.getDate() -7, 24, 0);
    let first_interval_end = new Date(now_date.getFullYear(), now_date.getMonth(), now_date.getDate(), 24, 0);
    document.getElementById('DateFrom').value = first_interval_start.toISOString().slice(0,10);
    document.getElementById('DateTo').value = first_interval_end.toISOString().slice(0,10);
function SelectButton(button){
    var url = '{% url "logistics:visualization" %}';
    let DateFrom = document.getElementById('DateFrom').value;
    let DateTo = document.getElementById('DateTo').value;
    let button_option = button.innerText
    get_data(url, {'DateFrom': DateFrom, 'DateTo': DateTo, 'button_option': button_option}).then(data => {Charts(data) });
}

async function get_data(url = '', data = {}) {
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });
            return response.json(); 
}

function Charts(data = {}) {
    var first_interval_chart = document.getElementById('first_interval_chart')
    var second_interval_chart = document.getElementById('second_interval_chart')

    if (Chart.getChart("first_interval_chart")) {
    Chart.getChart("first_interval_chart").destroy();
}
    if (Chart.getChart("second_interval_chart")) {
    Chart.getChart("second_interval_chart").destroy();
}

    var newLegendClickHandler = (e, legendItem, legend) => {
        const index = legendItem.datasetIndex;
        const ci = legend.chart;
        for (need_to_be_hidden in legend.legendItems){
            ci.hide(need_to_be_hidden)
        }
        ci.show(index)
        const paired_chart = Chart.getChart('second_interval_chart')
        const label_to_stay = legendItem.text
        const ci2 = paired_chart.legend.chart
        for (need_to_be_hidden in paired_chart.legend.legendItems){
            ci2.hide(need_to_be_hidden)
        }

        const paired_chart_labels = paired_chart.legend.legendItems
        for (i = 0; i < paired_chart_labels.length; i++) {
            label = paired_chart_labels[i].text
            if (label_to_stay == label) {
                ci2.show(i)
            }}
    }

    var newLegendClickHandler2 = (e, legendItem, legend) => {
        const index = legendItem.datasetIndex;
        const ci = legend.chart;
        for (need_to_be_hidden in legend.legendItems){
            ci.hide(need_to_be_hidden)
        }
        ci.show(index)
        const paired_chart = Chart.getChart('first_interval_chart')
        const label_to_stay = legendItem.text
        const ci2 = paired_chart.legend.chart
        for (need_to_be_hidden in paired_chart.legend.legendItems){
            ci2.hide(need_to_be_hidden)
        }

        const paired_chart_labels = paired_chart.legend.legendItems
        for (i = 0; i < paired_chart_labels.length; i++) {
            label = paired_chart_labels[i].text
            if (label_to_stay == label) {
                ci2.show(i)
            }}
    }

    const labels = data['days_in_range_first'];
    const chart_data = {
        labels: labels,
        datasets: data['datasets1'],
    }

    var myChart = new Chart(first_interval_chart, {
        type: 'line',
        data: chart_data,
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    onClick: newLegendClickHandler,
                },
                tooltip: {
                    callbacks: {
                        label: (context) => {
                            return [context.chart.data.datasets[context.datasetIndex].label, context.chart.data.datasets[context.datasetIndex].tooltips[context.dataIndex].split("|")[0], context.chart.data.datasets[context.datasetIndex].tooltips[context.dataIndex].split("|")[1]]
                        },
                    }
                }
            }
        }
    });

    const labels2 = data['days_in_range_second'];
    const chart_data2 = {
        labels: labels2,
        datasets: data['datasets2'],
    }

    var myChart = new Chart(second_interval_chart, {
        type: 'line',
        data: chart_data2,
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    onClick: newLegendClickHandler2,
                },
                tooltip: {
                    callbacks: {
                        label: (context) => {
                            return [context.chart.data.datasets[context.datasetIndex].label, context.chart.data.datasets[context.datasetIndex].tooltips[context.dataIndex].split("|")[0], context.chart.data.datasets[context.datasetIndex].tooltips[context.dataIndex].split("|")[1]]
                        },
                    }
                }
            }
        }
    });

    var barchart_dict = data['barchart_dict']
    var bar_chart = document.getElementById('bar_chart')

    if (Chart.getChart("bar_chart")) {
    Chart.getChart("bar_chart").destroy();
}
    var data_first_interval = []
    var data_second_interval = []
    for (key in barchart_dict) {
        data_first_interval.push(barchart_dict[key][1])
        data_second_interval.push(barchart_dict[key][2])
    }

    var myChart = new Chart(bar_chart, {
        type: 'bar',
        data: {
            labels: Object.keys(barchart_dict),
            datasets: [{
                label: 'Čas v intervalu celkem',
                backgroundColor: "#01263a",
                data: data_first_interval,
            },],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            tooltips: {
            displayColors: true,
            callbacks:{
                mode: 'index',
            },
            },
            scales: {
                x: {
                    stacked: true,
                    },
                y: {
                    stacked: true,
                    beginAtZero: true,
                    },
            }
            }
        });
}
</script>
{% endblock %}